"use client";
import { lazy, type ComponentType } from "react";

const components: Record<string, () => Promise<{ default: ComponentType<{ params?: Record<string, unknown> }> }>> = {
  radius: () => import("./RadiusTool"),
  distance: () => import("./DistanceTool"),
  bearing: () => import("./BearingMidpoint").then((m) => ({ default: m.BearingTool })),
  midpoint: () => import("./BearingMidpoint").then((m) => ({ default: m.MidpointTool })),
  matrix: () => import("./MatrixTool"),
  route: () => import("./RouteTool"),
  drivetime: () => import("./DriveTimeTool"),
  area: () => import("./AreaTool"),
  geocoder: () => import("./GeocoderTool"),
  iplookup: () => import("./IpLookupTool"),
  latlong: () => import("./LatLongTool"),
  converter: () => import("./ConverterTool"),
  fileviewer: () => import("./FileViewer"),
  csv: () => import("./CsvMapTool"),
  pinmap: () => import("./PinMapTool"),
  cities: () => import("./CitiesRadiusTool"),
  zipradius: () => import("./ZipRadiusTool"),
  nearby: () => import("./NearbyTool"),
  elevation: () => import("./ElevationTool"),
  horizon: () => import("./EarthTools").then((m) => ({ default: m.HorizonTool })),
  antipode: () => import("./EarthTools").then((m) => ({ default: m.AntipodeTool })),
  sun: () => import("./SunMoon").then((m) => ({ default: m.SunTool })),
  moon: () => import("./SunMoon").then((m) => ({ default: m.MoonTool })),
  geolines: () => import("./GeoLinesTool"),
  overpass: () => import("./OverpassNearest"),
  flight: () => import("./TripTools").then((m) => ({ default: m.FlightTimeTool })),
  fuel: () => import("./TripTools").then((m) => ({ default: m.FuelCostTool })),
  walkingtime: () => import("./TripTools").then((m) => ({ default: m.WalkingTimeTool })),
  nearestairport: () => import("./TripTools").then((m) => ({ default: m.NearestAirportTool })),
  tztool: () => import("./TimeExtra").then((m) => ({ default: m.TimezoneTool })),
  meeting: () => import("./TimeExtra").then((m) => ({ default: m.MeetingTool })),
  daylight: () => import("./TimeExtra").then((m) => ({ default: m.DaylightChartTool })),
  golden: () => import("./TimeExtra").then((m) => ({ default: m.GoldenHourTool })),
  unitconv: () => import("./ConvertersExtra").then((m) => ({ default: m.UnitConverterTool })),
  w3w: () => import("./ConvertersExtra").then((m) => ({ default: m.W3wTool })),
  addressval: () => import("./ConvertersExtra").then((m) => ({ default: m.AddressValidatorTool })),
  areacode: () => import("./UsLookups").then((m) => ({ default: m.AreaCodeTool })),
  census: () => import("./UsLookups").then((m) => ({ default: m.CensusTool })),
  watershed: () => import("./UsLookups").then((m) => ({ default: m.WatershedTool })),
  flood: () => import("./UsLookups").then((m) => ({ default: m.FloodTool })),
  quakes: () => import("./UsLookups").then((m) => ({ default: m.QuakeTool })),
  indigenous: () => import("./UsLookups").then((m) => ({ default: m.IndigenousTool })),
  solar: () => import("./EarthScience").then((m) => ({ default: m.SolarTool })),
  koppen: () => import("./EarthScience").then((m) => ({ default: m.ClimateZoneTool })),
  hardiness: () => import("./EarthScience").then((m) => ({ default: m.HardinessTool })),
  citycompare: () => import("./CompareTools").then((m) => ({ default: m.CityCompareTool })),
  col: () => import("./CompareTools").then((m) => ({ default: m.ColTool })),
  density: () => import("./CompareTools").then((m) => ({ default: m.DensityTool })),
  batchgeocode: () => import("./BatchGeocodeTool"),
  "growth-timezone": () => import("./GrowthTools").then((m) => ({ default: m.TimeZoneConverterTool })),
  "growth-flight": () => import("./GrowthTools").then((m) => ({ default: m.FlightDistanceTool })),
  "growth-meeting": () => import("./GrowthTools").then((m) => ({ default: m.MeetingPointTool })),
  "growth-mapscale": () => import("./GrowthTools").then((m) => ({ default: m.MapScaleTool })),
  "growth-bbox": () => import("./GrowthTools").then((m) => ({ default: m.BoundingBoxTool })),
  "growth-slope": () => import("./GrowthTools").then((m) => ({ default: m.SlopeGradientTool })),
  "growth-curvature": () => import("./GrowthTools").then((m) => ({ default: m.EarthCurvatureTool })),
  "growth-radio-los": () => import("./GrowthTools").then((m) => ({ default: m.RadioLosTool })),
  "growth-geojson-validator": () => import("./GrowthTools").then((m) => ({ default: m.GeoJsonValidatorTool })),
  "growth-gpx-csv": () => import("./GrowthTools").then((m) => ({ default: m.GpxToCsvTool })),
  "growth-gpx-merger": () => import("./GrowthTools").then((m) => ({ default: m.GpxMergerTool })),
  longtail: () => import("./LongtailTools"),
  longtail2: () => import("./LongtailTools2"),
  longtail3: () => import("./LongtailTools3"),
  longtail4: () => import("./LongtailTools4"),
  longtail6: () => import("./LongtailTools6"),
};

export const toolComponents: Record<string, ComponentType<{ params?: Record<string, unknown> }>> = Object.fromEntries(
  Object.entries(components).map(([k, loader]) => [k, lazy(loader)]),
);
