"use client";

import { useMemo, useState } from "react";
import { Field, Stat, ErrorBox } from "@/components/ui";

const fmt=(n:number,d=2)=>Number.isFinite(n)?n.toFixed(d):"—";
const n=(v:string)=>Number.isFinite(+v)?+v:0;
const R=6371.0088;
const rad=(x:number)=>x*Math.PI/180;
function hav(a:{lat:number,lng:number},b:{lat:number,lng:number}){const p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng);const h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(h));}

type Row={label:string;value:string;sub?:string};
function Two({aLabel,bLabel,a0,b0,calc}:{aLabel:string;bLabel:string;a0:number;b0:number;calc:(a:number,b:number)=>Row[]}){
 const[a,setA]=useState(String(a0)); const[b,setB]=useState(String(b0)); const rows=calc(n(a),n(b));
 return <div className="space-y-4"><div className="card grid gap-3 p-4 sm:grid-cols-2"><Field label={aLabel}><input className="input" type="number" value={a} onChange={e=>setA(e.target.value)}/></Field><Field label={bLabel}><input className="input" type="number" value={b} onChange={e=>setB(e.target.value)}/></Field></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{rows.map(r=><Stat key={r.label} label={r.label} value={r.value} sub={r.sub}/>)}</div></div>
}

function Trip({mode}:{mode:string}){
 if(mode==="roadtrip-speed")return <Two aLabel="Distance (km)" bLabel="Driving time (hours)" a0={600} b0={8} calc={(d,t)=>[{label:"Average speed",value:t>0?`${fmt(d/t)} km/h`:"—"},{label:"mph",value:t>0?`${fmt(d/t*0.621371)} mph`:"—"}]}/>;
 if(mode==="driving-hours-day")return <Two aLabel="Trip distance (km)" bLabel="Target km per day" a0={1200} b0={400} calc={(d,p)=>[{label:"Driving days",value:p>0?`${Math.ceil(d/p)} days`:"—"},{label:"Exact day equivalent",value:p>0?fmt(d/p):"—"}]}/>;
 if(mode==="trip-distance-day")return <Two aLabel="Total distance (km)" bLabel="Travel days" a0={1500} b0={4} calc={(d,days)=>[{label:"Distance per day",value:days>0?`${fmt(d/days)} km`:"—"},{label:"Miles per day",value:days>0?`${fmt(d/days*0.621371)} mi`:"—"}]}/>;
 if(mode==="fuel-cost-split")return <Two aLabel="Total fuel cost" bLabel="People" a0={180} b0={3} calc={(c,p)=>[{label:"Fuel cost per person",value:p>0?fmt(c/p):"—"},{label:"Total fuel cost",value:fmt(c)}]}/>;
 if(mode==="rest-stop-planner")return <Two aLabel="Trip distance (km)" bLabel="Stop every (km)" a0={800} b0={200} calc={(d,s)=>[{label:"Suggested en-route stops",value:s>0?String(Math.max(0,Math.ceil(d/s)-1)):"—"},{label:"Segments",value:s>0?String(Math.ceil(d/s)):"—"}]}/>;
 if(mode==="arrival-time")return <ArrivalTool/>;
 if(mode==="trip-buffer")return <Two aLabel="Base travel time (minutes)" bLabel="Buffer (%)" a0={180} b0={20} calc={(t,p)=>[{label:"Buffered travel time",value:`${fmt(t*(1+p/100),0)} min`},{label:"Added buffer",value:`${fmt(t*p/100,0)} min`}]}/>;
 if(mode==="roundtrip-time")return <Two aLabel="One-way distance (km)" bLabel="Average speed (km/h)" a0={250} b0={80} calc={(d,s)=>[{label:"Round-trip distance",value:`${fmt(d*2)} km`},{label:"Driving time",value:s>0?`${fmt(d*2/s)} h`:"—"}]}/>;
 return null;
}
function ArrivalTool(){const[start,setStart]=useState("2026-09-29T08:00"),[mins,setMins]=useState("360");const out=useMemo(()=>{const d=new Date(start);if(!Number.isFinite(d.getTime()))return null;return new Date(d.getTime()+n(mins)*60000)},[start,mins]);return <div className="space-y-4"><div className="card grid gap-3 p-4 sm:grid-cols-2"><Field label="Departure date & time"><input className="input" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="Travel time (minutes)"><input className="input" type="number" value={mins} onChange={e=>setMins(e.target.value)}/></Field></div>{out&&<Stat label="Estimated arrival" value={out.toLocaleString()}/>}</div>}

function Elevation({mode}:{mode:string}){
 if(mode==="lapse-rate")return <Two aLabel="Elevation change (m)" bLabel="Starting temperature (°C)" a0={1500} b0={25} calc={(h,t)=>[{label:"Standard-atmosphere estimate",value:`${fmt(t-h*0.0065,1)} °C`},{label:"Temperature change",value:`${fmt(-h*0.0065,1)} °C`}]}/>;
 if(mode==="pressure-altitude")return <Two aLabel="Station pressure (hPa)" bLabel="Reference sea-level pressure (hPa)" a0={900} b0={1013.25} calc={(p,p0)=>{const h=44330*(1-Math.pow(Math.max(.001,p/p0),0.1903));return[{label:"Pressure altitude",value:`${fmt(h,0)} m`},{label:"Feet",value:`${fmt(h*3.28084,0)} ft`}]} }/>;
 if(mode==="boiling-elevation")return <Two aLabel="Elevation (m)" bLabel="Reference only" a0={1500} b0={0} calc={(h)=>{const temp=100-h*0.003;return[{label:"Approx. boiling point",value:`${fmt(temp,1)} °C`},{label:"°F",value:`${fmt(temp*9/5+32,1)} °F`}]} }/>;
 if(mode==="vertical-speed")return <Two aLabel="Elevation change (m)" bLabel="Time (minutes)" a0={600} b0={90} calc={(h,t)=>[{label:"Vertical speed",value:t>0?`${fmt(h/(t/60),0)} m/h`:"—"},{label:"m/min",value:t>0?`${fmt(h/t,1)} m/min`:"—"}]}/>;
 if(mode==="relief-ratio")return <Two aLabel="Elevation range (m)" bLabel="Horizontal distance (km)" a0={800} b0={20} calc={(h,d)=>[{label:"Relief ratio",value:d>0?fmt(h/(d*1000),4):"—"},{label:"Percent",value:d>0?`${fmt(h/(d*1000)*100,2)}%`:"—"}]}/>;
 if(mode==="contour-count")return <Two aLabel="Elevation range (m)" bLabel="Contour interval (m)" a0={500} b0={20} calc={(h,i)=>[{label:"Approx. contour intervals",value:i>0?String(Math.floor(h/i)):"—"},{label:"Interval",value:`${fmt(i,1)} m`}]}/>;
 if(mode==="slope-length")return <Two aLabel="Horizontal run (m)" bLabel="Vertical rise (m)" a0={100} b0={20} calc={(run,rise)=>[{label:"Slope length",value:`${fmt(Math.hypot(run,rise))} m`},{label:"Slope angle",value:`${fmt(Math.atan2(rise,run)*180/Math.PI,2)}°`}]}/>;
 if(mode==="elevation-percent")return <Two aLabel="Elevation gain (m)" bLabel="Distance (km)" a0={450} b0={8} calc={(g,d)=>[{label:"Average gain per km",value:d>0?`${fmt(g/d,1)} m/km`:"—"},{label:"Average grade",value:d>0?`${fmt(g/(d*1000)*100,2)}%`:"—"}]}/>;
 return null;
}

function Precision({mode}:{mode:string}){
 if(mode==="decimal-precision")return <Two aLabel="Decimal places" bLabel="Latitude (°)" a0={5} b0={45} calc={(p,lat)=>{const step=111320/Math.pow(10,Math.max(0,Math.floor(p)));return[{label:"Latitude precision",value:`≈ ${fmt(step,3)} m`},{label:"Longitude precision",value:`≈ ${fmt(step*Math.cos(rad(lat)),3)} m`}]} }/>;
 if(mode==="latitude-span")return <Two aLabel="Latitude difference (°)" bLabel="Reference only" a0={1} b0={0} calc={(d)=>[{label:"North-south distance",value:`${fmt(Math.abs(d)*111.195,3)} km`},{label:"Miles",value:`${fmt(Math.abs(d)*69.093,3)} mi`}]}/>;
 if(mode==="longitude-span")return <Two aLabel="Longitude difference (°)" bLabel="Latitude (°)" a0={1} b0={45} calc={(d,lat)=>{const km=Math.abs(d)*111.32*Math.cos(rad(lat));return[{label:"East-west distance",value:`${fmt(km,3)} km`},{label:"Miles",value:`${fmt(km*0.621371,3)} mi`}]} }/>;
 if(mode==="coordinate-rounding")return <RoundingTool/>;
 return null;
}
function RoundingTool(){const[lat,setLat]=useState("40.712776"),[lng,setLng]=useState("-74.005974"),[p,setP]=useState("4");const places=Math.max(0,Math.min(8,Math.floor(n(p))));return <div className="space-y-4"><div className="card grid gap-3 p-4 sm:grid-cols-3"><Field label="Latitude"><input className="input" value={lat} onChange={e=>setLat(e.target.value)}/></Field><Field label="Longitude"><input className="input" value={lng} onChange={e=>setLng(e.target.value)}/></Field><Field label="Decimal places"><input className="input" type="number" min="0" max="8" value={p} onChange={e=>setP(e.target.value)}/></Field></div><Stat label="Rounded coordinate" value={`${n(lat).toFixed(places)}, ${n(lng).toFixed(places)}`}/></div>}

async function readGpx(file:File){const text=await file.text();const doc=new DOMParser().parseFromString(text,"application/xml");if(doc.querySelector("parsererror"))throw new Error("Invalid GPX/XML file");const pts=[...doc.querySelectorAll("trkpt,rtept,wpt")].map(el=>({el,lat:+(el.getAttribute("lat")||0),lng:+(el.getAttribute("lon")||0),ele:el.querySelector("ele")?.textContent?+(el.querySelector("ele")!.textContent||0):null,time:el.querySelector("time")?.textContent?new Date(el.querySelector("time")!.textContent||""):null}));return{doc,pts,text};}
function downloadDoc(doc:Document,name:string){const xml=new XMLSerializer().serializeToString(doc);const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([xml],{type:"application/gpx+xml"}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);}
function Gpx({mode}:{mode:string}){const[data,setData]=useState<any>(null),[err,setErr]=useState<string|null>(null);const load=async(f?:File)=>{if(!f)return;try{setData(await readGpx(f));setErr(null)}catch(e){setErr(e instanceof Error?e.message:"Invalid GPX")}};const stats=useMemo(()=>{if(!data)return null;const trk=[...data.doc.querySelectorAll("trk")].length,rte=[...data.doc.querySelectorAll("rte")].length,wpt=[...data.doc.querySelectorAll("wpt")].length;const coords=data.pts;let dist=0;for(let i=1;i<coords.length;i++)dist+=hav(coords[i-1],coords[i]);const lats=coords.map((p:any)=>p.lat),lngs=coords.map((p:any)=>p.lng);const times=coords.map((p:any)=>p.time?.getTime()).filter((x:any)=>Number.isFinite(x));return{trk,rte,wpt,count:coords.length,dist,bbox:coords.length?[Math.min(...lats),Math.min(...lngs),Math.max(...lats),Math.max(...lngs)]:null,start:coords[0],end:coords.at(-1),duration:times.length>1?(Math.max(...times)-Math.min(...times))/60000:0};},[data]);const action=()=>{if(!data)return;const doc=data.doc.cloneNode(true) as Document;if(mode==="gpx-shift-time"){const offset=3600000;doc.querySelectorAll("time").forEach((el:any)=>{const d=new Date(el.textContent||"");if(Number.isFinite(d.getTime()))el.textContent=new Date(d.getTime()+offset).toISOString();});downloadDoc(doc,"mapbench-shifted-time.gpx");return;}if(mode==="gpx-remove-waypoints"){doc.querySelectorAll("wpt").forEach((x:any)=>x.remove());downloadDoc(doc,"mapbench-no-waypoints.gpx");return;}};return <div className="space-y-3"><Field label="GPX file"><input className="input" type="file" accept=".gpx,application/gpx+xml,application/xml,text/xml" onChange={e=>load(e.target.files?.[0])}/></Field>{err&&<ErrorBox>{err}</ErrorBox>}{stats&&<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{mode==="gpx-track-count"&&<Stat label="Tracks" value={String(stats.trk)}/>} {mode==="gpx-route-count"&&<Stat label="Routes" value={String(stats.rte)}/>} {mode==="gpx-waypoint-count"&&<Stat label="Waypoints" value={String(stats.wpt)}/>} {mode==="gpx-bounds"&&<Stat label="Bounds (S,W,N,E)" value={stats.bbox?stats.bbox.map((x:number)=>fmt(x,5)).join(", "):"—"}/>} {mode==="gpx-start-end"&&<><Stat label="Start" value={stats.start?`${fmt(stats.start.lat,5)}, ${fmt(stats.start.lng,5)}`:"—"}/><Stat label="End" value={stats.end?`${fmt(stats.end.lat,5)}, ${fmt(stats.end.lng,5)}`:"—"}/></>} {mode==="gpx-total-points"&&<Stat label="Total coordinate points" value={String(stats.count)}/>} {mode==="gpx-total-distance"&&<Stat label="Approx. sequential distance" value={`${fmt(stats.dist,2)} km`}/>} {mode==="gpx-total-duration"&&<Stat label="Timestamp span" value={`${fmt(stats.duration,1)} min`}/>} {(mode==="gpx-shift-time"||mode==="gpx-remove-waypoints")&&<button className="btn btn-primary" onClick={action}>{mode==="gpx-shift-time"?"Download +1 hour GPX":"Download without waypoints"}</button>}</div>}</div>}

function Geo({mode}:{mode:string}){const[text,setText]=useState('{"type":"FeatureCollection","features":[]}');const parsed=useMemo(()=>{try{return{ok:true as const,v:JSON.parse(text)}}catch(e){return{ok:false as const,msg:e instanceof Error?e.message:"Invalid JSON"}}},[text]);const stats=useMemo(()=>{if(!parsed.ok)return null;const v=parsed.v;const features=v.type==="FeatureCollection"?(v.features||[]):v.type==="Feature"?[v]:[];const types:Record<string,number>={};const keys=new Set<string>();for(const f of features){const type=f?.geometry?.type||"null";types[type]=(types[type]||0)+1;Object.keys(f?.properties||{}).forEach(k=>keys.add(k));}return{features:features.length,types,keys:[...keys]};},[parsed]);return <div className="space-y-3"><Field label="GeoJSON"><textarea className="input min-h-56 font-mono text-xs" value={text} onChange={e=>setText(e.target.value)}/></Field>{!parsed.ok?<ErrorBox>{parsed.msg}</ErrorBox>:stats&&<div className="grid gap-2 sm:grid-cols-2">{mode==="geojson-geometry-count"&&<Stat label="Geometry counts" value={Object.entries(stats.types).map(([k,v])=>`${k}: ${v}`).join(" · ")||"None"}/>} {mode==="geojson-property-keys"&&<Stat label="Property keys" value={stats.keys.join(", ")||"None"}/>} {mode==="geojson-feature-total"&&<Stat label="Features" value={String(stats.features)}/>} {mode==="geojson-compact-size"&&<Stat label="Minified size" value={`${new Blob([JSON.stringify(parsed.v)]).size} bytes`}/>}</div>}</div>}

export default function LongtailTools4({params}:{params?:Record<string,unknown>}){const mode=String(params?.mode||"");if(["roadtrip-speed","driving-hours-day","trip-distance-day","fuel-cost-split","rest-stop-planner","arrival-time","trip-buffer","roundtrip-time"].includes(mode))return <Trip mode={mode}/>;if(["lapse-rate","pressure-altitude","boiling-elevation","vertical-speed","relief-ratio","contour-count","slope-length","elevation-percent"].includes(mode))return <Elevation mode={mode}/>;if(["decimal-precision","latitude-span","longitude-span","coordinate-rounding"].includes(mode))return <Precision mode={mode}/>;if(mode.startsWith("gpx-"))return <Gpx mode={mode}/>;if(mode.startsWith("geojson-"))return <Geo mode={mode}/>;return <ErrorBox>This calculator mode is not configured.</ErrorBox>}
