"use client";
import { useMemo, useState } from "react";
import { ErrorBox, Field, Stat } from "@/components/ui";
const R=6371.0088,rad=(d:number)=>d*Math.PI/180,deg=(r:number)=>r*180/Math.PI,fmt=(v:number,d=2)=>Number.isFinite(v)?v.toFixed(d):"—",mod=(n:number,m:number)=>((n%m)+m)%m;
function N({label,v,set}:{label:string;v:string;set:(x:string)=>void}){return <Field label={label}><input className="input" type="number" value={v} onChange={e=>set(e.target.value)}/></Field>}
function Two({a,b,av,bv,calc}:{a:string;b:string;av:number;bv:number;calc:(x:number,y:number)=>{label:string;value:string}[]}){const[x,sx]=useState(String(av)),[y,sy]=useState(String(bv));return <div className="space-y-4"><div className="card grid gap-3 p-4 sm:grid-cols-2"><N label={a} v={x} set={sx}/><N label={b} v={y} set={sy}/></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{calc(+x||0,+y||0).map(r=><Stat key={r.label} {...r}/>)}</div></div>}
function Three({labels,vals,calc}:{labels:[string,string,string];vals:[number,number,number];calc:(a:number,b:number,c:number)=>{label:string;value:string}[]}){const[a,sa]=useState(String(vals[0])),[b,sb]=useState(String(vals[1])),[c,sc]=useState(String(vals[2]));return <div className="space-y-4"><div className="card grid gap-3 p-4 md:grid-cols-3"><N label={labels[0]} v={a} set={sa}/><N label={labels[1]} v={b} set={sb}/><N label={labels[2]} v={c} set={sc}/></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{calc(+a||0,+b||0,+c||0).map(r=><Stat key={r.label} {...r}/>)}</div></div>}
export function PropertyGeometry2({mode}:{mode:string}){
 if(mode==="fence-length")return <Two a="Plot length (m)" b="Plot width (m)" av={50} bv={30} calc={(l,w)=>[{label:"Fence length",value:`${fmt(2*(l+w),1)} m`},{label:"Perimeter in feet",value:`${fmt(2*(l+w)*3.28084,1)} ft`}]} />;
 if(mode==="rectangle-acreage")return <Two a="Lot length (ft)" b="Lot width (ft)" av={200} bv={100} calc={(l,w)=>{const q=l*w;return[{label:"Area",value:`${fmt(q,0)} sq ft`},{label:"Acres",value:`${fmt(q/43560,4)} ac`},{label:"Hectares",value:`${fmt(q*0.0000092903,4)} ha`}];}}/>;
 if(mode==="crop-row-length")return <Three labels={["Field length (m)","Field width (m)","Row spacing (m)"]} vals={[100,60,.75]} calc={(l,w,s)=>{const n=s>0?Math.floor(w/s)+1:0;return[{label:"Approx. rows",value:String(n)},{label:"Total row length",value:`${fmt(n*l,0)} m`}];}}/>;
 if(mode==="seed-quantity")return <Two a="Area (acres)" b="Seeding rate (kg/acre)" av={10} bv={20} calc={(a,r)=>[{label:"Seed required",value:`${fmt(a*r,1)} kg`},{label:"Pounds",value:`${fmt(a*r*2.20462,1)} lb`}]} />;
 if(mode==="fertilizer-amount")return <Two a="Area (acres)" b="Application rate (lb/acre)" av={10} bv={100} calc={(a,r)=>[{label:"Fertilizer required",value:`${fmt(a*r,0)} lb`},{label:"Kilograms",value:`${fmt(a*r*.453592,1)} kg`}]} />;
 if(mode==="irrigation-coverage")return <Two a="Sprinkler radius (m)" b="Reference only" av={8} bv={0} calc={(r)=>[{label:"Ideal coverage",value:`${fmt(Math.PI*r*r,1)} m²`},{label:"Acres",value:`${fmt(Math.PI*r*r/4046.856,4)} ac`}]} />;
 if(mode==="sprinkler-count")return <Three labels={["Field area (m²)","Sprinkler radius (m)","Overlap (%)"]} vals={[5000,8,20]} calc={(a,r,o)=>{const one=Math.PI*r*r*Math.max(.1,1-o/100);return[{label:"Estimated sprinklers",value:String(one>0?Math.ceil(a/one):0)},{label:"Effective coverage each",value:`${fmt(one,1)} m²`}];}}/>;
 if(mode==="stock-density")return <Two a="Animals" b="Pasture area (acres)" av={20} bv={50} calc={(n,a)=>[{label:"Animals per acre",value:a>0?fmt(n/a,3):"—"},{label:"Acres per animal",value:n>0?fmt(a/n,2):"—"}]} />;
 if(mode==="circle-area-radius")return <Two a="Radius" b="Reference only" av={10} bv={0} calc={(r)=>[{label:"Area",value:fmt(Math.PI*r*r,4)},{label:"Circumference",value:fmt(2*Math.PI*r,4)}]} />;
 if(mode==="radius-from-area")return <Two a="Circle area" b="Reference only" av={314.159} bv={0} calc={(a)=>[{label:"Radius",value:fmt(Math.sqrt(Math.max(0,a)/Math.PI),4)},{label:"Diameter",value:fmt(2*Math.sqrt(Math.max(0,a)/Math.PI),4)}]} />;
 if(mode==="circumference-radius")return <Two a="Radius" b="Reference only" av={10} bv={0} calc={(r)=>[{label:"Circumference",value:fmt(2*Math.PI*r,4)},{label:"Diameter",value:fmt(2*r,4)}]} />;
 if(mode==="radius-from-circumference")return <Two a="Circumference" b="Reference only" av={62.8319} bv={0} calc={(c)=>[{label:"Radius",value:fmt(c/(2*Math.PI),4)},{label:"Diameter",value:fmt(c/Math.PI,4)}]} />;
 if(mode==="circle-overlap")return <Two a="Equal circle radius" b="Centre distance" av={10} bv={8} calc={(r,d)=>{if(r<=0||d>=2*r)return[{label:"Overlap area",value:"0"},{label:"Overlap",value:"0%"}];const area=2*r*r*Math.acos(d/(2*r))-.5*d*Math.sqrt(4*r*r-d*d);return[{label:"Overlap area",value:fmt(area,4)},{label:"Of one circle",value:`${fmt(area/(Math.PI*r*r)*100,2)}%`}];}}/>;
 return <CoordinateShape2 mode={mode}/>;
}
function parse(text:string){return text.split(/\n|;/).map(x=>x.trim()).filter(Boolean).map(x=>x.split(/[ ,]+/).map(Number)).filter(p=>p.length>=2&&Number.isFinite(p[0])&&Number.isFinite(p[1])).map(([lat,lng])=>({lat,lng}));}
function stats(p:{lat:number;lng:number}[]){if(p.length<3)return{area:0,per:0,cent:null as null|{lat:number;lng:number}};const lat0=p.reduce((s,x)=>s+x.lat,0)/p.length,c=Math.cos(rad(lat0)),xy=p.map(x=>({x:rad(x.lng)*R*c,y:rad(x.lat)*R}));let t=0,cx=0,cy=0,per=0;for(let i=0;i<xy.length;i++){const a=xy[i],b=xy[(i+1)%xy.length],q=a.x*b.y-b.x*a.y;t+=q;cx+=(a.x+b.x)*q;cy+=(a.y+b.y)*q;per+=Math.hypot(b.x-a.x,b.y-a.y);}const signed=t/2;return{area:Math.abs(signed),per,cent:Math.abs(signed)>1e-12?{lng:deg(cx/(6*signed)/R/c),lat:deg(cy/(6*signed)/R)}:null};}
function CoordinateShape2({mode}:{mode:string}){if(mode==="coordinate-radius-points")return <RadiusPoints/>;const[text,setText]=useState("40.7128,-74.0060\n40.7138,-74.0060\n40.7138,-74.0045\n40.7128,-74.0045"),p=useMemo(()=>parse(text),[text]),s=useMemo(()=>stats(p),[p]);const box=p.length?[Math.max(...p.map(x=>x.lat)),Math.min(...p.map(x=>x.lat)),Math.max(...p.map(x=>x.lng)),Math.min(...p.map(x=>x.lng))]:null;return <div className="space-y-3"><Field label="Latitude, longitude points"><textarea className="input min-h-52 font-mono text-xs" value={text} onChange={e=>setText(e.target.value)}/></Field>{p.length<2?<ErrorBox>Add valid coordinate pairs.</ErrorBox>:<div className="grid gap-2 sm:grid-cols-2">{mode==="polygon-area-coordinates"&&<Stat label="Approx. area" value={`${fmt(s.area,5)} km²`}/>} {mode==="polygon-perimeter-coordinates"&&<Stat label="Approx. perimeter" value={`${fmt(s.per,4)} km`}/>} {mode==="polygon-centroid-coordinates"&&<Stat label="Centroid" value={s.cent?`${fmt(s.cent.lat,6)}, ${fmt(s.cent.lng,6)}`:"—"}/>} {mode==="coordinate-bbox-generator"&&box&&<Stat label="N, S, E, W" value={box.map(v=>fmt(v,5)).join(", ")}/>}</div>}</div>}
function RadiusPoints(){const[lat,slat]=useState("40.7128"),[lng,slng]=useState("-74.006"),[r,sr]=useState("10"),[n,sn]=useState("8");const out=useMemo(()=>Array.from({length:Math.max(3,Math.min(360,+n||8))},(_,i)=>{const cnt=Math.max(3,Math.min(360,+n||8)),br=2*Math.PI*i/cnt,d=(+r||0)/R,p1=rad(+lat||0),l1=rad(+lng||0),p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(br)),l2=l1+Math.atan2(Math.sin(br)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return`${fmt(deg(p2),6)}, ${fmt(mod(deg(l2)+180,360)-180,6)}`;}),[lat,lng,r,n]);return <div className="space-y-3"><div className="card grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4"><N label="Centre latitude" v={lat} set={slat}/><N label="Centre longitude" v={lng} set={slng}/><N label="Radius (km)" v={r} set={sr}/><N label="Points" v={n} set={sn}/></div><Field label="Generated points"><textarea readOnly className="input min-h-48 font-mono text-xs" value={out.join("\n")}/></Field></div>}
