"use client";
import { useMemo, useState } from "react";
import { Field, Stat, ErrorBox } from "@/components/ui";

const R = 6371.0088;
const rad=(d:number)=>d*Math.PI/180, deg=(r:number)=>r*180/Math.PI;
const num=(v:string)=>Number.isFinite(+v)?+v:0;
const fmt=(v:number,d=2)=>Number.isFinite(v)?v.toFixed(d):"—";

function hav(a:{lat:number,lng:number},b:{lat:number,lng:number}){const p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng);const h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function walkCoords(x:any,out:number[][]=[]){if(Array.isArray(x)){if(x.length>=2&&typeof x[0]==="number"&&typeof x[1]==="number")out.push([x[0],x[1]]);else x.forEach(v=>walkCoords(v,out));}else if(x&&typeof x==="object")Object.values(x).forEach(v=>walkCoords(v,out));return out;}
function collectFeatures(g:any){return g?.type==="FeatureCollection"?g.features??[]:g?.type==="Feature"?[g]:g?.type?[{type:"Feature",properties:{},geometry:g}]:[];}
function geometrySegments(coords:any,out:number[][][]=[]){if(!Array.isArray(coords))return out;if(coords.length&&Array.isArray(coords[0])&&typeof coords[0][0]==="number")out.push(coords);else coords.forEach((c:any)=>geometrySegments(c,out));return out;}
function ringAreaKm2(ring:number[][]){if(ring.length<3)return 0;let s=0;for(let i=0;i<ring.length;i++){const a=ring[i],b=ring[(i+1)%ring.length];s+=rad(b[0]-a[0])*(2+Math.sin(rad(a[1]))+Math.sin(rad(b[1])));}return Math.abs(s)*R*R/2;}

function TwoNumber({aLabel,bLabel,a0,b0,onCalc}:{aLabel:string;bLabel:string;a0:number;b0:number;onCalc:(a:number,b:number)=>{label:string,value:string,sub?:string}[]}){const[a,setA]=useState(String(a0)),[b,setB]=useState(String(b0));const rows=onCalc(num(a),num(b));return <div className="space-y-4"><div className="card grid gap-3 p-4 sm:grid-cols-2"><Field label={aLabel}><input className="input" type="number" value={a} onChange={e=>setA(e.target.value)}/></Field><Field label={bLabel}><input className="input" type="number" value={b} onChange={e=>setB(e.target.value)}/></Field></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{rows.map(r=><Stat key={r.label} label={r.label} value={r.value} sub={r.sub}/>)}</div></div>}

function TextCoord({mode}:{mode:string}){const[text,setText]=useState("40.7128, -74.0060");const result=useMemo(()=>{const m=text.trim().match(/^\s*([+-]?\d+(?:\.\d+)?)\s*[, ]\s*([+-]?\d+(?:\.\d+)?)\s*$/);if(!m)return null;const lat=+m[1],lng=+m[2];return{lat,lng,valid:lat>=-90&&lat<=90&&lng>=-180&&lng<=180};},[text]);if(mode==="coordinate-parser"||mode==="coordinate-format-detector"||mode==="latlng-validator")return <div className="space-y-3"><Field label="Coordinates"><input className="input" value={text} onChange={e=>setText(e.target.value)} placeholder="40.7128, -74.0060"/></Field>{result?<div className="grid gap-2 sm:grid-cols-3"><Stat label="Latitude" value={fmt(result.lat,6)}/><Stat label="Longitude" value={fmt(result.lng,6)}/><Stat label={mode==="coordinate-format-detector"?"Detected format":"Validation"} value={mode==="coordinate-format-detector"?"Decimal degrees (lat, lng)":result.valid?"Valid WGS84 range":"Out of range"}/></div>:<ErrorBox>Enter decimal latitude and longitude separated by a comma or space.</ErrorBox>}</div>;
return null;}

function CoordinateMath({mode}:{mode:string}){if(mode==="coordinate-destination") {const[lat,setLat]=useState("40.7128"),[lng,setLng]=useState("-74.006"),[bearing,setBearing]=useState("90"),[distance,setDistance]=useState("100");const r=useMemo(()=>{const p1=rad(num(lat)),l1=rad(num(lng)),br=rad(num(bearing)),d=num(distance)/R;const p2=Math.asin(Math.sin(p1)*Math.cos(d)+Math.cos(p1)*Math.sin(d)*Math.cos(br));const l2=l1+Math.atan2(Math.sin(br)*Math.sin(d)*Math.cos(p1),Math.cos(d)-Math.sin(p1)*Math.sin(p2));return{lat:deg(p2),lng:((deg(l2)+540)%360)-180};},[lat,lng,bearing,distance]);return <div className="space-y-4"><div className="card grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Start latitude"><input className="input" value={lat} onChange={e=>setLat(e.target.value)}/></Field><Field label="Start longitude"><input className="input" value={lng} onChange={e=>setLng(e.target.value)}/></Field><Field label="Bearing (°)"><input className="input" value={bearing} onChange={e=>setBearing(e.target.value)}/></Field><Field label="Distance (km)"><input className="input" value={distance} onChange={e=>setDistance(e.target.value)}/></Field></div><Stat label="Destination coordinate" value={`${fmt(r.lat,6)}, ${fmt(r.lng,6)}`}/></div>}
if(mode==="coordinate-offset")return <TwoNumber aLabel="North/South offset (km)" bLabel="East/West offset (km)" a0={1} b0={1} onCalc={(n,e)=>[{label:"Approx. latitude change",value:`${fmt(n/111.32,6)}°`},{label:"Approx. longitude change at equator",value:`${fmt(e/111.32,6)}°`}]} />;
if(mode==="lat-degree-km")return <TwoNumber aLabel="Degrees latitude" bLabel="Reference only" a0={1} b0={0} onCalc={(a)=>[{label:"Distance",value:`${fmt(a*111.195,3)} km`},{label:"Miles",value:`${fmt(a*69.093,3)} mi`}]} />;
if(mode==="lng-degree-km")return <TwoNumber aLabel="Degrees longitude" bLabel="Latitude (°)" a0={1} b0={45} onCalc={(d,lat)=>{const km=d*111.32*Math.cos(rad(lat));return[{label:"Distance",value:`${fmt(Math.abs(km),3)} km`},{label:"Miles",value:`${fmt(Math.abs(km)*0.621371,3)} mi`}]} />;
return null;}

function PaceTool({mode}:{mode:string}){if(mode==="hiking-time")return <TwoNumber aLabel="Distance (km)" bLabel="Elevation gain (m)" a0={10} b0={500} onCalc={(d,g)=>{const h=d/5+Math.max(0,g)/600;return[{label:"Naismith estimate",value:`${fmt(h,2)} h`,sub:"distance/5 + ascent/600"},{label:"Minutes",value:`${fmt(h*60,0)} min`}]} />;
if(mode==="hiking-pace"||mode==="walking-pace")return <TwoNumber aLabel="Distance (km)" bLabel="Time (minutes)" a0={5} b0={60} onCalc={(d,t)=>[{label:"Pace",value:d>0?`${fmt(t/d,2)} min/km`:"—"},{label:"Speed",value:t>0?`${fmt(d/(t/60),2)} km/h`:"—"}]} />;
if(mode==="cycling-time")return <TwoNumber aLabel="Distance (km)" bLabel="Average speed (km/h)" a0={30} b0={20} onCalc={(d,s)=>[{label:"Ride time",value:s>0?`${fmt(d/s,2)} h`:"—"},{label:"Minutes",value:s>0?`${fmt(d/s*60,0)} min`:"—"}]} />;
if(mode==="cycling-speed")return <TwoNumber aLabel="Distance (km)" bLabel="Time (minutes)" a0={20} b0={60} onCalc={(d,t)=>[{label:"Average speed",value:t>0?`${fmt(d/(t/60),2)} km/h`:"—"},{label:"Pace",value:d>0?`${fmt(t/d,2)} min/km`:"—"}]} />;
if(mode==="walk-calories"||mode==="cycle-calories")return <TwoNumber aLabel="Body weight (kg)" bLabel="Distance (km)" a0={70} b0={5} onCalc={(w,d)=>{const factor=mode==="walk-calories"?0.55:0.32;return[{label:"Estimated calories",value:`${fmt(w*d*factor,0)} kcal`,sub:"rough planning estimate"},{label:"Per km",value:`${fmt(w*factor,0)} kcal/km`}]} />;
return null;}

function LandTripTool({mode}:{mode:string}){if(mode==="land-cost-acre")return <TwoNumber aLabel="Total land price" bLabel="Area (acres)" a0={100000} b0={5} onCalc={(p,a)=>[{label:"Cost per acre",value:a>0?fmt(p/a,2):"—"},{label:"Cost per hectare",value:a>0?fmt(p/(a*0.404686),2):"—"}]} />;
if(mode==="land-cost-sqft")return <TwoNumber aLabel="Total property price" bLabel="Lot area (sq ft)" a0={250000} b0={10000} onCalc={(p,a)=>[{label:"Cost per sq ft",value:a>0?fmt(p/a,2):"—"},{label:"Cost per m²",value:a>0?fmt(p/(a*0.092903),2):"—"}]} />;
if(mode==="trip-cost-person")return <TwoNumber aLabel="Total trip cost" bLabel="People" a0={600} b0={4} onCalc={(c,p)=>[{label:"Cost per person",value:p>0?fmt(c/p,2):"—"},{label:"Total",value:fmt(c,2)}]} />;
if(mode==="fuel-needed")return <TwoNumber aLabel="Distance (km)" bLabel="Fuel economy (L/100 km)" a0={500} b0={7} onCalc={(d,e)=>[{label:"Fuel needed",value:`${fmt(d*e/100,2)} L`},{label:"US gallons",value:`${fmt(d*e/100/3.78541,2)} gal`}]} />;
if(mode==="roundtrip-fuel")return <TwoNumber aLabel="One-way distance (km)" bLabel="Fuel economy (L/100 km)" a0={200} b0={7} onCalc={(d,e)=>[{label:"Round-trip distance",value:`${fmt(d*2,1)} km`},{label:"Fuel needed",value:`${fmt(d*2*e/100,2)} L`}]} />;
if(mode==="liters-distance")return <TwoNumber aLabel="Distance (km)" bLabel="Consumption (L/100 km)" a0={300} b0={8} onCalc={(d,e)=>[{label:"Liters required",value:`${fmt(d*e/100,2)} L`}]} />;
if(mode==="gallons-distance")return <TwoNumber aLabel="Distance (miles)" bLabel="Fuel economy (MPG)" a0={300} b0={30} onCalc={(d,e)=>[{label:"Gallons required",value:e>0?`${fmt(d/e,2)} gal`:"—"}]} />;
if(mode==="cost-mile"||mode==="cost-km")return <TwoNumber aLabel="Total cost" bLabel={mode==="cost-mile"?"Distance (miles)":"Distance (km)"} a0={100} b0={250} onCalc={(c,d)=>[{label:mode==="cost-mile"?"Cost per mile":"Cost per km",value:d>0?fmt(c/d,3):"—"}]} />;
if(mode==="knots-time")return <TwoNumber aLabel="Distance (nautical miles)" bLabel="Speed (knots)" a0={120} b0={20} onCalc={(d,s)=>[{label:"Travel time",value:s>0?`${fmt(d/s,2)} h`:"—"},{label:"Minutes",value:s>0?`${fmt(d/s*60,0)} min`:"—"}]} />;
return null;}

function EarthTool({mode}:{mode:string}){if(mode==="earth-bulge")return <TwoNumber aLabel="Chord / sightline distance (km)" bLabel="Reference only" a0={20} b0={0} onCalc={(d)=>{const half=d*1000/2;const bulge=R*1000-Math.sqrt((R*1000)**2-half**2);return[{label:"Midpoint bulge",value:`${fmt(bulge,2)} m`},{label:"Feet",value:`${fmt(bulge*3.28084,2)} ft`}]} />;
if(mode==="hidden-height")return <TwoNumber aLabel="Distance (km)" bLabel="Observer height (m)" a0={20} b0={2} onCalc={(d,h)=>{const drop=(d*1000)**2/(2*R*1000);return[{label:"Curvature drop",value:`${fmt(drop,2)} m`},{label:"Approx. hidden beyond observer height",value:`${fmt(Math.max(0,drop-h),2)} m`}]} />;
if(mode==="fresnel")return <TwoNumber aLabel="Link distance (km)" bLabel="Frequency (GHz)" a0={10} b0={5} onCalc={(d,f)=>{const r=8.657*Math.sqrt(Math.max(0,d)/(4*Math.max(.001,f)));return[{label:"1st Fresnel radius at midpoint",value:`${fmt(r,2)} m`},{label:"60% clearance target",value:`${fmt(r*.6,2)} m`}]} />;
if(mode==="fresnel-clearance")return <TwoNumber aLabel="First Fresnel radius (m)" bLabel="Available clearance (m)" a0={10} b0={6} onCalc={(r,c)=>[{label:"Clearance",value:r>0?`${fmt(c/r*100,1)}%`:"—"},{label:"Typical target",value:"≥ 60%"}]} />;
if(mode==="antenna-height")return <TwoNumber aLabel="Required radio horizon distance (km)" bLabel="Other antenna height (m)" a0={30} b0={10} onCalc={(d,h2)=>{const needed=Math.max(0,d/4.12-Math.sqrt(Math.max(0,h2)));return[{label:"Required antenna 1 height",value:`${fmt(needed**2,2)} m`},{label:"Model",value:"4/3-Earth horizon"}]} />;
if(mode==="pressure-elevation")return <TwoNumber aLabel="Elevation (m)" bLabel="Sea-level pressure (hPa)" a0={1000} b0={1013.25} onCalc={(h,p0)=>{const p=p0*(1-2.25577e-5*h)**5.25588;return[{label:"Estimated pressure",value:`${fmt(p,1)} hPa`},{label:"Percent of sea level",value:`${fmt(p/p0*100,1)}%`}]} />;
if(mode==="temp-elevation")return <TwoNumber aLabel="Elevation change (m)" bLabel="Starting temperature (°C)" a0={1000} b0={20} onCalc={(h,t)=>[{label:"Standard lapse estimate",value:`${fmt(t-h/1000*6.5,1)} °C`},{label:"Temperature change",value:`${fmt(-h/1000*6.5,1)} °C`}]} />;
return null;}

function GeoJsonTool({mode}:{mode:string}){const[text,setText]=useState('{\n  "type": "FeatureCollection",\n  "features": []\n}');const parsed=useMemo(()=>{try{return{ok:true as const,v:JSON.parse(text)}}catch(e){return{ok:false as const,e:e instanceof Error?e.message:"Invalid JSON"}}},[text]);const stats=useMemo(()=>{if(!parsed.ok)return null;const f=collectFeatures(parsed.v),coords=walkCoords(parsed.v);let length=0,area=0;for(const ft of f){const g=ft.geometry;if(!g)continue;for(const seg of geometrySegments(g.coordinates)){for(let i=1;i<seg.length;i++)length+=haversine({lat:seg[i-1][1],lng:seg[i-1][0]},{lat:seg[i][1],lng:seg[i][0]});if(g.type==="Polygon"||g.type==="MultiPolygon")area+=ringAreaKm2(seg);}}const lngs=coords.map(c=>c[0]),lats=coords.map(c=>c[1]);return{features:f.length,coords:coords.length,bbox:coords.length?[Math.min(...lngs),Math.min(...lats),Math.max(...lngs),Math.max(...lats)]:null,centroid:coords.length?[lngs.reduce((a,b)=>a+b,0)/lngs.length,lats.reduce((a,b)=>a+b,0)/lats.length]:null,length,area};},[parsed]);if(mode==="geojson-format"||mode==="geojson-minify"){const output=parsed.ok?JSON.stringify(parsed.v,null,mode==="geojson-format"?2:0):"";return <div className="space-y-3"><Field label="GeoJSON"><textarea className="input min-h-56 font-mono text-xs" value={text} onChange={e=>setText(e.target.value)}/></Field>{parsed.ok?<Field label={mode==="geojson-format"?"Formatted output":"Minified output"}><textarea readOnly className="input min-h-40 font-mono text-xs" value={output}/></Field>:<ErrorBox>{parsed.e}</ErrorBox>}</div>}
return <div className="space-y-3"><Field label="GeoJSON"><textarea className="input min-h-56 font-mono text-xs" value={text} onChange={e=>setText(e.target.value)}/></Field>{!parsed.ok?<ErrorBox>{parsed.e}</ErrorBox>:stats&&<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{mode==="geojson-feature-count"&&<Stat label="Features" value={String(stats.features)}/>} {mode==="geojson-coordinate-count"&&<Stat label="Coordinate pairs" value={String(stats.coords)}/>} {mode==="geojson-bbox"&&<Stat label="Bounding box" value={stats.bbox?stats.bbox.map(v=>fmt(v,5)).join(", "):"—"}/>} {mode==="geojson-centroid"&&<Stat label="Mean coordinate centre" value={stats.centroid?`${fmt(stats.centroid[1],5)}, ${fmt(stats.centroid[0],5)}`:"—"}/>} {mode==="geojson-area"&&<Stat label="Approx. polygon area" value={`${fmt(stats.area,3)} km²`}/>} {mode==="geojson-length"&&<Stat label="Approx. line/ring length" value={`${fmt(stats.length,3)} km`}/>}</div>}</div>}

async function parseGpx(file:File){const txt=await file.text();const doc=new DOMParser().parseFromString(txt,"application/xml");if(doc.querySelector("parsererror"))throw new Error("Invalid GPX/XML file");const pts=[...doc.querySelectorAll("trkpt,rtept")].map(p=>({lat:+(p.getAttribute("lat")||0),lng:+(p.getAttribute("lon")||0),ele:p.querySelector("ele")?.textContent?+(p.querySelector("ele")!.textContent||0):null,time:p.querySelector("time")?.textContent?new Date(p.querySelector("time")!.textContent||""):null,node:p}));return{txt,doc,pts};}
function GpxTool({mode}:{mode:string}){const[data,setData]=useState<any>(null),[err,setErr]=useState<string|null>(null);const load=async(f?:File)=>{if(!f)return;try{setData(await parseGpx(f));setErr(null)}catch(e){setErr(e instanceof Error?e.message:"Invalid GPX")}};const stats=useMemo(()=>{if(!data)return null;let distance=0,gain=0,loss=0,maxSpeed=0;for(let i=1;i<data.pts.length;i++){const a=data.pts[i-1],b=data.pts[i],d=haversine(a,b);distance+=d;if(a.ele!=null&&b.ele!=null){const de=b.ele-a.ele;if(de>0)gain+=de;else loss-=de;}if(a.time&&b.time){const h=(b.time-a.time)/3600000;if(h>0)maxSpeed=Math.max(maxSpeed,d/h);}}const times=data.pts.map((p:any)=>p.time?.getTime()).filter((x:any)=>Number.isFinite(x));const duration=times.length>1?(Math.max(...times)-Math.min(...times))/3600000:0;return{distance,gain,loss,duration,avg:duration>0?distance/duration:0,maxSpeed,points:data.pts.length};},[data]);const download=(kind:string)=>{if(!data)return;const clone=data.doc.cloneNode(true) as Document;if(kind==="reverse"){clone.querySelectorAll("trkseg").forEach((s:any)=>{[...s.children].reverse().forEach((n:any)=>s.appendChild(n));});}if(kind==="strip-time")clone.querySelectorAll("time").forEach((n:any)=>n.remove());if(kind==="strip-ele")clone.querySelectorAll("ele").forEach((n:any)=>n.remove());const xml=new XMLSerializer().serializeToString(clone);const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([xml],{type:"application/gpx+xml"}));a.download=`mapbench-${kind}.gpx`;a.click();URL.revokeObjectURL(a.href);};return <div className="space-y-3"><Field label="GPX file"><input className="input" type="file" accept=".gpx,application/gpx+xml,application/xml,text/xml" onChange={e=>load(e.target.files?.[0])}/></Field>{err&&<ErrorBox>{err}</ErrorBox>}{stats&&<div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{mode==="gpx-distance"&&<Stat label="Track distance" value={`${fmt(stats.distance,2)} km`}/>} {mode==="gpx-gain"&&<Stat label="Elevation gain" value={`${fmt(stats.gain,0)} m`}/>} {mode==="gpx-loss"&&<Stat label="Elevation loss" value={`${fmt(stats.loss,0)} m`}/>} {mode==="gpx-duration"&&<Stat label="Duration" value={`${fmt(stats.duration,2)} h`}/>} {mode==="gpx-avg-speed"&&<Stat label="Average speed" value={`${fmt(stats.avg,2)} km/h`}/>} {mode==="gpx-max-speed"&&<Stat label="Maximum segment speed" value={`${fmt(stats.maxSpeed,2)} km/h`}/>} {mode==="gpx-point-count"&&<Stat label="Track / route points" value={String(stats.points)}/>} {(mode==="gpx-reverse"||mode==="gpx-strip-time"||mode==="gpx-strip-ele")&&<button className="btn btn-primary" onClick={()=>download(mode==="gpx-reverse"?"reverse":mode==="gpx-strip-time"?"strip-time":"strip-ele")}>{mode==="gpx-reverse"?"Download reversed GPX":mode==="gpx-strip-time"?"Download without timestamps":"Download without elevation"}</button>}</div>}</div>}

export default function LongtailTool({params}:{params?:Record<string,unknown>}){const mode=String(params?.mode||"");if(["hiking-time","hiking-pace","walking-pace","cycling-time","cycling-speed","walk-calories","cycle-calories"].includes(mode))return <PaceTool mode={mode}/>;if(["land-cost-acre","land-cost-sqft","trip-cost-person","fuel-needed","roundtrip-fuel","liters-distance","gallons-distance","cost-mile","cost-km","knots-time"].includes(mode))return <LandTripTool mode={mode}/>;if(["coordinate-destination","coordinate-offset","lat-degree-km","lng-degree-km"].includes(mode))return <CoordinateMath mode={mode}/>;if(["coordinate-parser","coordinate-format-detector","latlng-validator"].includes(mode))return <TextCoord mode={mode}/>;if(mode.startsWith("geojson-"))return <GeoJsonTool mode={mode}/>;if(mode.startsWith("gpx-"))return <GpxTool mode={mode}/>;if(["earth-bulge","hidden-height","fresnel","fresnel-clearance","antenna-height","pressure-elevation","temp-elevation"].includes(mode))return <EarthTool mode={mode}/>;return <ErrorBox>This calculator mode is not configured.</ErrorBox>}
